ArtProject/Pages/Combined.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ArtProject.DataLayer;
using ArtProject.Models;
using ArtProject.Services;
using Azure;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ArtProject.Pages
{
    public class CombinedModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public IEnumerable<UserModel> UsersListing;
        public CombinedModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public ExhibitionModel exhData { get; set; }

        [BindProperty]
        public IEnumerable<UserExhModel> UsersExh { get; set; }

        [BindProperty]
        public List<SingleExhModel> Exh { get; set; }

        [BindProperty]
        public List<SingleExhModel> ExhList { get; set; }


        public void OnGet(ArtService artService)
        {
            //UsersListing = _db.TableUnitMaster;

            //string receivedValue = TempData["MyValue"] as string;

            //if (receivedValue != null || userLogged == null || User.Identity.Name != null)
            //{
            //    isLogged = true;


            //    //userLogged = UsersListing.Where(user => user.Username.Equals(receivedValue)).ToList()[0];
            //    //Console.WriteLine(userLogged.Username);
            //    //TempData.Remove("MyValue");
            //    exhData = artService.GetExhibitionModel();
            //}

            UsersListing = _db.TableUnitMaster;
            UsersExh = _db.UserExhTable;
            Console.WriteLine("xxx");

            string receivedValue = TempData["MyValue"] as string;

            if (receivedValue != null || userLogged == null || User.Identity.Name != null)
            {
                isLogged = true;
                Console.WriteLine("qqqqqq");

                //userLogged = UsersListing.Where(user => user.Username.Equals(receivedValue)).ToList()[0];
                //Console.WriteLine(userLogged.Username);
                //TempData.Remove("MyValue");

                ExhList = new List<SingleExhModel>();



                Console.WriteLine(UsersExh.Count());
                exhData = artService.GetExhibitionModel();

                for (var i = 0; i < UsersExh.Count(); i++)
                {

                    string Selected = UsersExh.ElementAt(i).Username.Trim();

                    if (Selected.Equals(User.Identity.Name))
                    {
                        if (artService.GetSingleExhibition(Int32.Parse(UsersExh.ElementAt(i).ExhId)) != null)
                        {
                            ExhList.Add(artService.GetSingleExhibition(Int32.Parse(UsersExh.ElementAt(i).ExhId)));
                        }
                    }

                }
                Console.WriteLine(ExhList.Count);

            }


            else { Console.WriteLine("else"); }
        }

        [BindProperty]
        public List<UserModel> Users { get; set; }

        [BindProperty]
        public UserModel userLogged { get; set; }

        [BindProperty]
        public bool isLogged { get; set; }

        [BindProperty]
        public string UserName { get; set; }

        [BindProperty]
        public bool CanEdit { get; set; }

        public async Task<IActionResult> OnPostDeleteRequest()
        {
            UsersListing = _db.TableUnitMaster;
            Console.WriteLine(UserName);
            UserModel DeleteUser = UsersListing.First(pt => pt.Username == UserName);
            _db.TableUnitMaster.Remove(DeleteUser);
            _db.SaveChanges();

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostLogOutRequest()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/Index");
        }

        [BindProperty]
        public UserModel ChangeUser { get; set; }

        [BindProperty]
        public int ChangeId { get; set; }

        [BindProperty]
        public string CName { get; set; }

        [BindProperty]
        public string CEmail { get; set; }

        [BindProperty]
        public int CAge { get; set; }

        [BindProperty]
        public string CUsername { get; set; }

        [BindProperty]
        public string CPassword { get; set; }


        public IActionResult OnPostEditRequest()
        {
            UsersListing = _db.TableUnitMaster;

            //ChangeUser = UsersListing.FirstOrDefault(x => x.Id == Id);
            //Console.WriteLine(ChangeUser.Id);


            //if (ChangeUser != null)
            //{
            //    ChangeUser.Name = CName;
            //    ChangeUser.Username = CUsername;
            //    ChangeUser.Email = CEmail;
            //    ChangeUser.Password = CPassword;
            //    ChangeUser.Age = CAge;
            //}

            //_db.SaveChanges();

            Console.WriteLine(ChangeId);
            Console.WriteLine(UsersListing.ElementAt(2).Id);
            ChangeUser = UsersListing.SingleOrDefault(user => user.Id == ChangeId);
            //Console.WriteLine(ChangeUser.Id);

            if (ChangeUser != null)
            {
                ChangeUser.Name = CName;
                ChangeUser.Username = User.Identity.Name;
                ChangeUser.Email = CEmail;
                ChangeUser.Password = CPassword;
                ChangeUser.Age = CAge;
            }

            _db.SaveChanges();



            var claims = new List<Claim>
                    {
                    new Claim(ClaimTypes.Name, ChangeUser.Username),
                    new Claim(ClaimTypes.Role, "User")
                    };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authProperties = new AuthenticationProperties();

            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

            return RedirectToPage("Index");
        }

    }
}

ArtProject/Pages/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ArtProject.Pages
{
    public class DetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ArtProject/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ArtProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ArtProject/Pages/LogIn.cshtml.cs
using ArtProject.DataLayer;
using ArtProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using System.Linq;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;

namespace ArtProject.Pages
{
    public class LogInModel : PageModel
    {
        //[BindProperty]
        //public string Username { get; set; }
        //[BindProperty]
        //public string Password { get; set; }


        //public IActionResult OnPostLoginRequest()
        //{
        //    string path = @"UserData.json";

        //    var existingData = new List<UserModel>();

        //    if (System.IO.File.Exists(path))
        //    {
        //        var json = System.IO.File.ReadAllText(path);
        //        existingData = JsonSerializer.Deserialize<List<UserModel>>(json);
        //    }


        //    List<string> usernames = existingData.Select(person => person.Username).ToList();

        //    List<string> passwords = existingData.Select(person => person.Password).ToList();


        //    if (usernames.Contains(Username))
        //    {
        //        if (passwords.Contains(Password))
        //        {
        //            string valueToSend = Username;
        //            Console.WriteLine($"login successful");
        //            TempData["MyValue"] = valueToSend;
        //            return RedirectToPage("Profile");
        //        }
        //    }

        //    else
        //    {
        //        return RedirectToPage("Login");
        //    }

        //    return RedirectToPage("Index");
        //}


        [BindProperty]
        public string Username { get; set; }
        [BindProperty]
        public string Password { get; set; }

        private readonly ApplicationDbContext _db;

        public IEnumerable<UserModel> UsersListing;

        public LogInModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> OnPostLoginRequest()
        {
            UsersListing = _db.TableUnitMaster;

            var usernames = UsersListing.Select(pt => pt.Username).ToList();
            var passwords = UsersListing.Select(pt => pt.Password);


            if (usernames.Contains(Username))
            {
                if (passwords.Contains(Password))
                {
                    Console.WriteLine("pass dogru");
                    string valueToSend = Username;
                    Console.WriteLine($"login successful");
                    TempData["MyValue"] = valueToSend;
                    //return RedirectToPage("Profile");


                    var claims = new List<Claim>
                    {
                    new Claim(ClaimTypes.Name, Username),
                    new Claim(ClaimTypes.Role, "User")
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties();

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
                    return RedirectToPage("/Index");
                }
            }

            else
            {
                return RedirectToPage("Login");
            }

            return RedirectToPage("Index");
        }



        public void OnGet()
        {
            UsersListing = _db.TableUnitMaster;
        }

    }
}

ArtProject/Pages/Search.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http;
using static System.Formats.Asn1.AsnWriter;
using System.Text.RegularExpressions;
using ArtProject.Services;
using ArtProject.Models;
using static ArtProject.Models.PainterPhotoModel;
using static ArtProject.Models.ArtModel;
using System.Reflection;

namespace ArtProject.Pages
{
    public class SearchModel : PageModel
    {

        [BindProperty]
        public string SearchKeyword { get; set; }

        [BindProperty]
        public string painterImage { get; set; }

        [BindProperty]
        public string painterText { get; set; }

        [BindProperty]
        public string artistName { get; set; }

        [BindProperty]
        public List<string> Images { get; set; } = new List<string>();

        [BindProperty]
        public List<string> ImageNames { get; set; } = new List<string>();
        PainterPhotoModel painterPhotoModel { get; set; }
        ArtModel artModel { get; set; }
        PaintModel paintModel { get; set; }

        ArtModel artistModel { get; set; }
        PaintModel painterModel { get; set; }



        public void OnGet()
        {

        }
        public void OnPostSearchRequest(ArtService artService)
        {

            artModel = artService.GetArtModelOneSample(SearchKeyword);
            paintModel = artService.GetPaintModel(artModel.data.FirstOrDefault().api_link);
            var painterName = paintModel.data.artist_title;
            painterName = Regex.Replace(painterName, @"\s", "_");
            painterPhotoModel = artService.GetPainterPhotoModel(painterName);

            painterImage = painterPhotoModel.query.pages.FirstOrDefault().Value.thumbnail.source.ToString();
            painterText = painterPhotoModel.query.pages.FirstOrDefault().Value.extract.ToString();
            artistName = paintModel.data.artist_title.ToString();


            artistModel = artService.GetArtModel(SearchKeyword);
            foreach (var datum in artistModel.data)
            {
                painterModel = artService.GetPaintModel(datum.api_link.ToString());
                var url = "https://www.artic.edu/iiif/2/" + painterModel.data.image_id + "/full/843,/0/default.jpg";
                Images.Add(url);

                ImageNames.Add(painterModel.data.title);

            }

        }

    }
}

ArtProject/Pages/SignUp.cshtml.cs
using ArtProject.DataLayer;
using ArtProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace ArtProject.Pages
{
    public class SignUpModel : PageModel
    {
        //[BindProperty]
        //public List<UserModel> Users { get; set; }

        //[BindProperty]
        //public string Name { get; set; }

        //[BindProperty]
        //public int Age { get; set; }

        //[BindProperty]
        //public string Email { get; set; }

        //[BindProperty]
        //public string Username { get; set; }

        //[BindProperty]
        //public string Password { get; set; }



        //public IActionResult OnPostUserRequest()
        //{
        //    string path = @"UserData.json";

        //    var newData = new UserModel(Name, Age, Email, Username, Password);


        //    var existingData = new List<UserModel>();

        //    if (System.IO.File.Exists(path))
        //    {
        //        var json = System.IO.File.ReadAllText(path);
        //        existingData = JsonSerializer.Deserialize<List<UserModel>>(json);
        //    }


        //    existingData.Add(newData);


        //    var updatedJson = JsonSerializer.Serialize(existingData);
        //    Console.WriteLine(updatedJson);
        //    //System.IO.File.WriteAllText(jsonData, updatedJson);



        //    using (var tw = new StreamWriter(path, false))
        //    {
        //        tw.WriteLine(updatedJson.ToString());
        //        tw.Close();
        //    }


        //    return RedirectToPage("Index");
        //}
        //public void OnGet()
        //{
        //}

        [BindProperty]
        public List<UserModel> Users { get; set; }

        [BindProperty]
        public string Name { get; set; }

        [BindProperty]
        public int Age { get; set; }

        [BindProperty]
        public string Email { get; set; }

        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        [BindProperty]
        public int Id { get; set; }


        private readonly ApplicationDbContext _db;

        public IEnumerable<UserModel> UsersListing;
        //public List<UserModel> UsersListing;

        public SignUpModel(ApplicationDbContext db)
        {
            _db = db;
        }



        public async Task<IActionResult> OnPostUserRequest()
        {

            UsersListing = _db.TableUnitMaster;

            var newData = new UserModel(Name, Age, Email, Username, Password, Id);

            await _db.TableUnitMaster.AddAsync(newData);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");


        }
        public void OnGet()
        {
        }
    }
}

ArtProject/Pages/Ticket.cshtml.cs
using AngleSharp.Html.Parser;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using ArtProject.DataLayer;
using ArtProject.Models;
using ArtProject.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ArtProject.Pages
{

    public class TicketModel : PageModel
    {

        [BindProperty]
        public SingleExhModel Exhibition { get; set; }

        [BindProperty]
        public int ExhId { get; set; }

        public string Username { get; set; }

        public int Id { get; set; }

        private readonly ApplicationDbContext _db;

        public IEnumerable<UserExhModel> UsersExhListing;

        public TicketModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> OnPostBuyRequest()
        {
            await Console.Out.WriteLineAsync(ExhId.ToString());
            Username = User.Identity.Name;
            UserExhModel deneme = new(Username, ExhId.ToString(), Id);

            await _db.UserExhTable.AddAsync(deneme);
            await _db.SaveChangesAsync();

            return RedirectToPage("Profile");
        }

        public void OnGet(int id, ArtService artService)
        {
            UsersExhListing = _db.UserExhTable;

            ExhId = id;

            Exhibition = artService.GetSingleExhibition(id);
            Username = User.Identity.Name;
            //Console.WriteLine(Username);

           
            var doc = new HtmlParser();
            if (!string.IsNullOrEmpty(Exhibition.data.short_description))
                Exhibition.data.short_description = Regex.Replace(Exhibition.data.short_description, @"<[^>]*>", String.Empty);
            
        }
    }
}

ArtProject/Pages/Combined.cshtml
@page
@model ArtProject.Pages.CombinedModel
@{
    ViewData["Title"] = "Combined";
}

<h1>Combined</h1>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ArtProject/Pages/LogIn.cshtml
@page
@model ArtProject.Pages.LogInModel
@{
}



    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-content">
                    <h1 class="display-1">Log In</h1>
                    
                    <form method="post" asp-page-handler="LoginRequest" class="d-flex flex-column" style="width:50%;padding:10px;margin-top:30px;">
					<input type="text" asp-for="Username" placeholder="User Name" class="form-control form-control-lg"/>
                    <input type="password" asp-for="Password" placeholder="Password" class="form-control form-control-lg" style="margin-top:15px" />
					<button type="submit" class="btn" style="background-color:#E15686;margin-top:15px; font-weight:600; font-size:20px">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

	@*<div class="container">
		<div class="col-md-12">
		<form class="form-horizontal templatemo-login-form-2" method="post" asp-page-handler="LoginRequest">
				<div class="row">
					<div class="col-md-12">
						<h1>Login Form Two</h1>
					</div>
				</div>
				<div class="row">
					<div class="templatemo-one-signin col-md-6">
						<div class="form-group">
							<div class="col-md-12">
								<label for="username" class="control-label">Username</label>
								<div class="templatemo-input-icon-container">
									<i class="fa fa-user"></i>
									<input type="text" class="form-control" id="username" placeholder="">
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<label for="password" class="control-label">Password</label>
								<div class="templatemo-input-icon-container">
									<i class="fa fa-lock"></i>
									<input type="password" class="form-control" id="password" placeholder="">
								</div>
							</div>
						</div>
					
						<div class="form-group">
							<div class="col-md-12">
								<input type="submit" class="btn btn-warning">
							</div>
						</div>
						
					</div>
				</div>
			</form>
		</div>
	</div>*@

ArtProject/Pages/Search.cshtml
@page
@model ArtProject.Pages.SearchModel
@{
}

<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-12" style="margin-top:130px">
                <form asp-page-handler="SearchRequest" method="post" class="w-100">
                    <div class="p-1 bg-dark rounded rounded-pill shadow-sm mb-4">
                        <div class="input-group">
                            <input type="search" asp-for="SearchKeyword" placeholder="Search Painter" aria-describedby="button-addon1" class="form-control border-0">
                            <div class="input-group-append">
                                <button id="button-addon1" type="submit" class="btn btn-link text-primary">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                                    </svg>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-12">
                <div class="page-content">
                    <div class="row" style="margin-bottom:10px">
                        <div class="col-lg-12" style="margin-bottom:10px">
                            <h1>@Model.artistName</h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="feature-banner header-text">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <img src="@Model.painterImage" alt="" style="border-radius: 23px;">
                                    </div>
                                    <div class="col-lg-8">
                                        <article><p>@Model.painterText</p></article>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="game-details">
                        <div class="row">
                            <div class="col-lg-12">
                                <h2>Artworks</h2>
                            </div>
                            <div class="col-lg-12">
                                <div class="content">
                                    <div class="container">
                                        <div class="row row-cols-3" style="margin-top:15px">
                                            @for (int i = 0; i < Model.Images.Count; i++)
                                            {
                                                <div class="col-lg-4 col-sm-6">
                                                    <div class="item">
                                                        <div class="thumb">
                                                            <img src="@Model.Images[i]" width="350" height="350" alt="">
                                                            <div class="hover-effect">
                                                                <div class="content">
                                                                    <ul>
                                                                        <li style="color:pink">@Model.ImageNames[i]</li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</body>

ArtProject/Pages/SetProfile.cshtml
@page
@model ArtProject.Pages.SetProfileModel
@{
}

<body>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-content">
                    <h1 class="display-1">Welcome</h1>
                    <div class="d-flex justify-content-around">
                        <a asp-page="SignUp">Sign Up</a>
                        <div>
                            <h5 class="display-5">Already have an account?</h5>
                            <a asp-page="LogIn">Log In</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

ArtProject/Pages/SignUp.cshtml
@*@page
    @model ArtProject.Pages.SignUpModel
    @{
    }

    <style>
        form{
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            text-align: center;
        }

        .page-content{

        }
    </style>

    <body>

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="page-content">
                        <h1 class="display-1">Sign Up</h1>

                        <form method="post" asp-page-handler="UserRequest">
                            <input type="text" asp-for="Name" placeholder="Name"/>
                            <input type="text" asp-for="Age" placeholder="Age" />
                            <input type="text" asp-for="Email" placeholder="Email"/>
                            <input type="text" asp-for="Username" placeholder="Username"/>
                            <input type="password" asp-for="Password" placeholder="Password"/>
                            <button type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </body>*@

@page
@model ArtProject.Pages.SignUpModel
@{
}

<body>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-content">
                    <h1 class="display-1">Sign Up</h1>
                    <form method="post" class="formClass" asp-page-handler="UserRequest">
                        <input type="text" asp-for="Name" class="form-control" placeholder="Name" />
                        <input type="text" asp-for="Age" class="form-control" placeholder="Age" />
                        <input type="text" asp-for="Email" class="form-control" placeholder="Email" />
                        <input type="text" asp-for="Username" class="form-control" placeholder="Username" />
                        <input type="password" asp-for="Password" class="form-control" placeholder="Password" />
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</body>

<style>
    .form-control {
        max-width: 30%;
        margin: 10px;
        margin-left: auto;
        margin-right: auto;
    }

    .col-lg-12 {
        text-align: center;
    }

    .formClass button {
        margin-top: 20px;
    }

    .display-1 {
        margin-bottom: 30px;
    }
</style>

ArtProject/Pages/Ticket.cshtml
@page
@model ArtProject.Pages.TicketModel
@{
}

<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-content">

                    <!-- ***** Banner Start ***** -->
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="main-profile ">
                                <div class="row">
                                    <div class="col-lg-4" style="width: 100%; height: 250px; overflow: hidden; display: flex; justify-content: center; align-items: center">
                                        <img src=@Model.Exhibition.data.image_url alt="" style="border-radius: 23px; width:100%;">
                                    </div>
                                    <div style="width:100%; display:flex; justify-content:space-around; align-items:center; margin-top:40px">
                                        <div class="col-lg-4 align-self-center" style="width:50%">
                                            <div class="main-info header-text">
                                                <h4>@Model.Exhibition.data.title</h4>
                                                <p>@Model.Exhibition.data.short_description</p>
                                                <form method="post" class="formClass center" asp-page-handler="BuyRequest">
                                                    <div class="d-flex flex-column" style="width:50%;">
                                                        <span style="width:auto; text-align:center;">                                                         
                                                            <button type="submit" style="border:none; background:none; color:white;">Buy Ticket</button>
                                                            <input type="hidden" asp-for="ExhId" name="ExhId" value=@Model.Exhibition.data.id>
                                                        </span>

                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 align-self-center" style="width:40%">
                                            <ul>
                                                <li>Start Date <span>@Model.Exhibition.data.aic_start_at</span></li>
                                                <li>End Date <span>@Model.Exhibition.data.aic_end_at</span></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<style>

.center {
    margin-left: auto;
    margin-right: auto;
    text-align: center;
    display: flex;
    justify-content: center;
    margin-top: 10px;
}

</style>

ArtProject/Pages/Users.cshtml
@page
@model ArtProject.Pages.UsersModel
@{
}

<div style="margin:100px">
    <h1>Users</h1>

    <ul>
        @foreach (var item in Model.UsersListing)
        {
            <li style="color:white">username: @item.Username</li>
            <li style="color:white">password: @item.Password</li>
        }
    </ul>
</div>